name: uafw
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  footer: ^0.0.4
  open_filex: ^4.3.2
  page_transition: ^2.0.9
  provider: ^6.0.5
  rflutter_alert: ^2.0.7
  url_launcher: ^6.1.12
  flutter_hooks: ^0.18.0
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  cloud_firestore: ^4.8.4
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^5.7.2+3
  collection: ^1.17.1
  flutter_countdown_timer: ^4.1.0
  flutter_timer_countdown: ^1.0.5
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - docs/
